// Build step: emit app/themes.generated.css from lib/theme/tokens.ts so the
// 14 theme palettes ship as a single CSS file with `[data-theme="..."]`
// selectors. Run by `predev` and `prebuild` scripts in package.json.
//
// Why: writing all 14 selectors by hand would be tedious and error-prone.
// Editing tokens.ts is the single source of truth; this script keeps the CSS
// vars in sync.
//
// Run: `npx tsx lib/theme/__build__.ts`

import fs from "node:fs";
import path from "node:path";
import { TR1VIA_THEMES, type ThemeKey } from "./tokens";
import { resolveTheme } from "./resolve";

const OUT = path.join(process.cwd(), "app", "themes.generated.css");

const lines: string[] = [
  "/* GENERATED by lib/theme/__build__.ts. Do not edit by hand. */",
  "/* Source: lib/theme/tokens.ts */",
  "",
];

for (const key of Object.keys(TR1VIA_THEMES) as ThemeKey[]) {
  const def = TR1VIA_THEMES[key];
  const r = resolveTheme(key);
  lines.push(`:root[data-theme="${key}"] {`);
  lines.push(`  --paper: ${def.paper};`);
  lines.push(`  --ink: ${def.ink};`);
  lines.push(`  --accent: ${def.accent};`);
  lines.push(`  --pop: ${def.pop};`);
  lines.push(`  --correct: ${def.correct};`);
  lines.push(`  --wrong: ${def.wrong};`);
  lines.push(`  --surface: ${r.surface};`);
  lines.push(`  --surface-h: ${r.surfaceH};`);
  lines.push(`  --ink-mid: ${r.inkMid};`);
  lines.push(`  --ink-mute: ${r.inkMute};`);
  lines.push(`  --line: ${r.line};`);
  lines.push(`  --line-soft: ${r.lineSoft};`);
  lines.push(`  color-scheme: ${def.mode};`);
  lines.push("}");
  lines.push("");
}

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, lines.join("\n"));
console.log(`Wrote ${OUT} (${Object.keys(TR1VIA_THEMES).length} themes)`);
