// Procedural lightning — Apple/Pixar-grade strikes for the May "storm"
// theme. Replaces the old radial-gradient flicker with:
//
//   • An overlay canvas rendered above whatever's behind, drawn with
//     multi-stage flashes (leader → return stroke → 1-3 subsequents →
//     afterglow). Each stroke has its own jagged geometry generated by
//     `lightning-bolt.ts`.
//   • Procedural color evolution per stroke: white core, blue-white inner
//     glow, purple halo, yellow-orange afterglow.
//   • Full-scene illumination flash on the return stroke — a translucent
//     overlay that fades in / holds / fades out over ~140ms total. Kept
//     under 30% relative luminance shift so it stays WCAG-safe.
//   • Procedural thunder from `lib/audio/thunder.ts` with distance-aware
//     delay (sound travels slower than light).
//
// Two tiers fire automatically:
//   1. Ambient — Poisson-distributed distant flashes off the top edge.
//      Bursts: 30% chance of 1-3 follow-up strikes within 0.5-3s.
//   2. Beat-triggered — close, dramatic strikes when the parent bumps
//      `triggerCount`. Used at section-complete + finale.
//
// Accessibility:
//   • Honors `prefers-reduced-motion: reduce` → renders the legacy soft
//     glow instead (`LegacyFlicker` below). No procedural strikes fire.
//   • Hard rate cap (`MAX_STRIKES_PER_MINUTE`) prevents pathological loops.

"use client";

import { useEffect, useRef } from "react";
import { usePrefersReducedMotion } from "@/lib/hooks/usePrefersReducedMotion";
import {
  generateBolt,
  generateSubsequentStroke,
  sampleExponentialInterval,
  type BoltSegment,
} from "./lightning-bolt";
import { playThunder, unlockThunder } from "@/lib/audio/thunder";

// ─── Module-level beat trigger ────────────────────────────────────────────
// Game-state callsites (section-complete celebration, finale mount, etc.)
// call `fireLightningBeat()` directly. Every mounted Lightning instance is
// subscribed and fires a close strike. Module-level rather than React-prop
// because the Weather/Lightning tree lives 3-4 levels inside each TVStage,
// and each TV* view wraps its own TVStage — threading a prop through every
// component for one global trigger isn't worth the surface area.
//
// Multiple Lightning instances can be mounted (e.g., HostLiveConsole has
// the embedded TVStateMachine plus the host's own surface). All fire on
// the same beat — same in-page event, same room reaction. Last-write-wins
// across simultaneous broadcasts isn't a concern.

type BeatListener = (distance: "distant" | "close", opts?: { tint?: string }) => void;
const beatListeners = new Set<BeatListener>();

/** Subscribe to lightning-beat events. Returns an unsubscribe function. */
function subscribeBeat(fn: BeatListener): () => void {
  beatListeners.add(fn);
  return () => beatListeners.delete(fn);
}

/**
 * Fire a beat-triggered lightning strike across every mounted Lightning
 * instance. Used at section-complete (one close strike) and finale
 * (multiple staggered close strikes). No-op if no Lightning is mounted
 * (non-May themes won't have one).
 *
 * Safe to call from any callsite — handles SSR (no-ops if window is
 * undefined since listeners can only register on mount).
 *
 * @param opts.tint  Per-strike color hex (e.g. a player's brand color).
 *   When provided, the halo + afterglow blend toward this color while the
 *   hot white core stays white. Ignored for ambient background strikes.
 */
export function fireLightningBeat(
  distance: "distant" | "close" = "close",
  opts?: { tint?: string },
): void {
  for (const fn of beatListeners) fn(distance, opts);
}

export interface LightningProps {
  /** Accent color used for the residual afterglow. Defaults to May's
   *  amber so the brand tint reads on the lingering flash. */
  color?: string;
  /**
   * Per-strike color tint. When provided, the halo + afterglow blend toward
   * this color while the hot core stays white. Used by lock-in ceremonies
   * to make each player's strike feel like THEIRS.
   *
   * Applied as the default for ALL beat-triggered strikes on this instance.
   * Can be overridden per-call via `fireLightningBeat("close", { tint })`.
   * Ambient background strikes are never tinted — they're the storm, not a
   * player moment.
   */
  tint?: string;
  /** Bump this counter to fire a beat-triggered close strike. */
  triggerCount?: number;
  /** Disable ambient strikes entirely (still fires beat strikes). Used
   *  by the dev demo when the designer just wants to inspect on-demand
   *  strikes. */
  disableAmbient?: boolean;
  /** Disable thunder audio. The visual still plays. */
  muteThunder?: boolean;
}

interface Strike {
  /** All strokes within this strike. Each stroke has its own geometry. */
  strokes: Stroke[];
  /** Strike start time (performance.now). */
  startMs: number;
  /** Distance flavor — drives illumination intensity + thunder timing. */
  distance: "distant" | "close";
  /** When `true`, the scene-illumination flash has been fired for this
   *  strike (set after the return stroke begins). */
  illuminationFired: boolean;
  /** When `true`, the thunder has been scheduled. */
  thunderFired: boolean;
  /** Strike origin / target in canvas pixels at gen time. Pinned per
   *  strike so subsequent strokes share the trunk path. */
  originX: number;
  originY: number;
  targetX: number;
  targetY: number;
  /** Strike seed. Subsequent strokes derive from this. */
  seed: number;
  /**
   * Optional color tint for this specific strike. Set only on beat-triggered
   * strikes when a tint was passed via fireLightningBeat or the component's
   * tint prop. Ambient strikes always leave this undefined so the background
   * storm stays neutral.
   */
  tint?: string;
}

interface Stroke {
  segments: BoltSegment[];
  /** Stroke start offset from the strike start (ms). */
  startOffsetMs: number;
  /** Stroke duration (ms). */
  durationMs: number;
  /** Peak alpha (0-1). Leader is dim, return stroke is bright. */
  peakAlpha: number;
  /** Is this the return stroke (the bright primary)? Drives illumination. */
  isReturnStroke: boolean;
}

interface SceneFlash {
  /** Flash start ms (performance.now). */
  startMs: number;
  /** Total visible duration ms (fade in + hold + fade out). */
  durationMs: number;
  /** Peak alpha (kept <0.32 for WCAG safety). */
  peakAlpha: number;
}

// ── Tuning constants ──────────────────────────────────────────────────────

const AMBIENT_MEAN_INTERVAL_MS = 45_000;     // Poisson mean
const BURST_CHANCE = 0.3;                    // chance an ambient strike triggers a burst
const BURST_FOLLOWUPS_MIN = 1;
const BURST_FOLLOWUPS_MAX = 3;
const BURST_DELAY_MIN_MS = 500;
const BURST_DELAY_MAX_MS = 3000;

// Hard rate ceiling (per CLAUDE.md a11y note — <6 close strikes/min;
// ambient counts separately and stays under 20/min by exponential law).
const MAX_STRIKES_PER_MINUTE = 30;

// Color palette (per spec).
const CORE_COLOR = "rgba(255, 255, 255, 1)";
const INNER_GLOW_COLOR = "rgba(208, 232, 255, 0.9)";
const OUTER_HALO_COLOR = "rgba(156, 123, 200, 0.4)";
// Afterglow is composited in screen-blend with the theme accent.
const AFTERGLOW_DEFAULT = "rgba(232, 196, 106, 0.18)";

// Scene illumination — kept under 30% relative luminance shift.
const SCENE_FLASH_PEAK_ALPHA = 0.28; // ~28% over the existing scene
const SCENE_FLASH_FADE_IN_MS = 30;
const SCENE_FLASH_HOLD_MS = 50;
const SCENE_FLASH_FADE_OUT_MS = 60;

export function Lightning({
  color = "#E8C46A",
  tint,
  triggerCount = 0,
  disableAmbient = false,
  muteThunder = false,
}: LightningProps) {
  const reduced = usePrefersReducedMotion();
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const flashOverlayRef = useRef<HTMLDivElement | null>(null);
  const strikesRef = useRef<Strike[]>([]);
  const sceneFlashRef = useRef<SceneFlash | null>(null);
  const rafIdRef = useRef<number | null>(null);
  const ambientTimerRef = useRef<number | null>(null);
  const lastTriggerRef = useRef(triggerCount);
  const strikeHistoryRef = useRef<number[]>([]); // ms timestamps of recent strikes

  // ── Beat-triggered strike: when triggerCount bumps, fire a close one ──
  useEffect(() => {
    if (reduced) return;
    if (triggerCount === lastTriggerRef.current) return;
    lastTriggerRef.current = triggerCount;
    if (triggerCount > 0) {
      // Tiny delay so we're past React commit before generating geometry.
      const id = window.setTimeout(() => fireStrike("close", muteThunder, tint), 16);
      return () => clearTimeout(id);
    }
  }, [triggerCount, reduced, muteThunder, tint]);

  // ── Module-level beat subscription ──
  // Game-state callsites (section-complete celebration) call
  // `fireLightningBeat()` to trigger strikes without prop-threading.
  useEffect(() => {
    if (reduced) return;
    const unsubscribe = subscribeBeat((distance, opts) => {
      // Tiny delay so any state-change React commit settles before geometry
      // generation reads canvas dimensions.
      // The effective tint is: caller-supplied opts.tint → prop tint → none.
      const effectiveTint = opts?.tint ?? tint;
      window.setTimeout(() => fireStrike(distance, muteThunder, effectiveTint), 16);
    });
    return unsubscribe;
  }, [reduced, muteThunder, tint]);

  // ── Ambient Poisson timer ──
  useEffect(() => {
    if (reduced || disableAmbient) return;
    let cancelled = false;

    function scheduleNext() {
      if (cancelled) return;
      const intervalMs = Math.max(
        4_000,
        sampleExponentialInterval(AMBIENT_MEAN_INTERVAL_MS),
      );
      ambientTimerRef.current = window.setTimeout(() => {
        if (cancelled) return;
        fireStrike("distant", muteThunder);
        // Burst chance — 1-3 follow-ups within 0.5-3s.
        if (Math.random() < BURST_CHANCE) {
          const followups =
            BURST_FOLLOWUPS_MIN +
            Math.floor(Math.random() * (BURST_FOLLOWUPS_MAX - BURST_FOLLOWUPS_MIN + 1));
          for (let i = 0; i < followups; i++) {
            const burstDelay =
              BURST_DELAY_MIN_MS +
              Math.random() * (BURST_DELAY_MAX_MS - BURST_DELAY_MIN_MS);
            window.setTimeout(() => {
              if (cancelled) return;
              fireStrike("distant", muteThunder);
            }, burstDelay);
          }
        }
        scheduleNext();
      }, intervalMs);
    }

    // First strike: 2-8s after mount so the room sees activity early without
    // feeling busy.
    ambientTimerRef.current = window.setTimeout(() => {
      if (cancelled) return;
      fireStrike("distant", muteThunder);
      scheduleNext();
    }, 2_000 + Math.random() * 6_000);

    return () => {
      cancelled = true;
      if (ambientTimerRef.current !== null) {
        clearTimeout(ambientTimerRef.current);
      }
    };
  }, [reduced, disableAmbient, muteThunder]);

  // ── Canvas RAF loop ──
  useEffect(() => {
    if (reduced) return;
    const canvas = canvasRef.current;
    if (!canvas) return;
    const dpr = Math.min(window.devicePixelRatio || 1, 2);

    function resize() {
      const c = canvasRef.current;
      if (!c) return;
      const parent = c.parentElement;
      if (!parent) return;
      const w = parent.clientWidth;
      const h = parent.clientHeight;
      c.width = Math.max(1, Math.floor(w * dpr));
      c.height = Math.max(1, Math.floor(h * dpr));
      c.style.width = `${w}px`;
      c.style.height = `${h}px`;
    }
    resize();

    let ro: ResizeObserver | null = null;
    if (typeof ResizeObserver !== "undefined" && canvas.parentElement) {
      ro = new ResizeObserver(resize);
      ro.observe(canvas.parentElement);
    } else {
      window.addEventListener("resize", resize);
    }

    const ctx2d = canvas.getContext("2d");
    if (!ctx2d) return;

    function render() {
      const c = canvasRef.current;
      const cx = c?.getContext("2d");
      if (!c || !cx) return;

      cx.clearRect(0, 0, c.width, c.height);
      cx.setTransform(dpr, 0, 0, dpr, 0, 0);

      const now = performance.now();
      const liveStrikes: Strike[] = [];

      for (const strike of strikesRef.current) {
        const elapsed = now - strike.startMs;
        const lastStroke = strike.strokes[strike.strokes.length - 1];
        if (!lastStroke) continue;
        // Strike "lifetime" runs to ~150ms past the last stroke (afterglow).
        const totalLifetime = lastStroke.startOffsetMs + lastStroke.durationMs + 150;
        if (elapsed > totalLifetime) continue;

        // Did the return stroke just begin? If so, fire scene illumination.
        if (!strike.illuminationFired) {
          const rs = strike.strokes.find((s) => s.isReturnStroke);
          if (rs && elapsed >= rs.startOffsetMs) {
            strike.illuminationFired = true;
            if (strike.distance === "close") {
              sceneFlashRef.current = {
                startMs: now,
                durationMs: SCENE_FLASH_FADE_IN_MS + SCENE_FLASH_HOLD_MS + SCENE_FLASH_FADE_OUT_MS,
                peakAlpha: SCENE_FLASH_PEAK_ALPHA,
              };
            } else {
              // Distant strikes get a much fainter scene illumination —
              // suggests the storm without blowing out the room.
              sceneFlashRef.current = {
                startMs: now,
                durationMs: 120,
                peakAlpha: 0.08,
              };
            }
          }
        }

        // Render each stroke if it's within its window.
        for (const stroke of strike.strokes) {
          const strokeElapsed = elapsed - stroke.startOffsetMs;
          if (strokeElapsed < 0 || strokeElapsed > stroke.durationMs + 100) continue;
          // Envelope: 25% fade-in, 50% sustain, 25% fade-out.
          const t = strokeElapsed / stroke.durationMs;
          let alpha = 0;
          if (t < 0.25) alpha = (t / 0.25) * stroke.peakAlpha;
          else if (t < 0.75) alpha = stroke.peakAlpha;
          else if (t < 1) alpha = stroke.peakAlpha * (1 - (t - 0.75) / 0.25);
          else {
            // Afterglow: residual amber/purple lingers briefly.
            const lingerT = (strokeElapsed - stroke.durationMs) / 100;
            alpha = stroke.peakAlpha * 0.08 * Math.max(0, 1 - lingerT);
          }
          if (alpha <= 0) continue;
          drawStroke(cx, stroke, alpha, color, strike.distance, strike.tint);
        }

        liveStrikes.push(strike);
      }
      strikesRef.current = liveStrikes;

      // Update scene-flash overlay opacity (HTML element to avoid canvas
      // sizing limitations with full-viewport fills).
      const overlay = flashOverlayRef.current;
      if (overlay) {
        const sf = sceneFlashRef.current;
        if (!sf) {
          overlay.style.opacity = "0";
        } else {
          const elapsed = now - sf.startMs;
          let a = 0;
          if (elapsed < SCENE_FLASH_FADE_IN_MS) {
            a = (elapsed / SCENE_FLASH_FADE_IN_MS) * sf.peakAlpha;
          } else if (elapsed < SCENE_FLASH_FADE_IN_MS + SCENE_FLASH_HOLD_MS) {
            a = sf.peakAlpha;
          } else if (elapsed < sf.durationMs) {
            const fade =
              (elapsed - SCENE_FLASH_FADE_IN_MS - SCENE_FLASH_HOLD_MS) /
              Math.max(1, sf.durationMs - SCENE_FLASH_FADE_IN_MS - SCENE_FLASH_HOLD_MS);
            a = sf.peakAlpha * (1 - fade);
          } else {
            sceneFlashRef.current = null;
            a = 0;
          }
          overlay.style.opacity = String(a);
        }
      }

      rafIdRef.current = requestAnimationFrame(render);
    }

    rafIdRef.current = requestAnimationFrame(render);

    return () => {
      if (rafIdRef.current !== null) cancelAnimationFrame(rafIdRef.current);
      if (ro) ro.disconnect();
      else window.removeEventListener("resize", resize);
    };
  }, [reduced, color]);

  // ── Unlock audio on the first user interaction ──
  useEffect(() => {
    if (reduced || muteThunder) return;
    let unlocked = false;
    function tryUnlock() {
      if (unlocked) return;
      unlocked = true;
      void unlockThunder();
      window.removeEventListener("pointerdown", tryUnlock);
      window.removeEventListener("keydown", tryUnlock);
    }
    window.addEventListener("pointerdown", tryUnlock, { passive: true });
    window.addEventListener("keydown", tryUnlock);
    return () => {
      window.removeEventListener("pointerdown", tryUnlock);
      window.removeEventListener("keydown", tryUnlock);
    };
  }, [reduced, muteThunder]);

  // ── Reduced motion: render the legacy soft glow, no procedural strikes ──
  if (reduced) {
    return <LegacyFlicker color={color} />;
  }

  function fireStrike(distance: "distant" | "close", mute: boolean, strikeTint?: string) {
    // Rate limit.
    const now = performance.now();
    const recent = strikeHistoryRef.current.filter((t) => now - t < 60_000);
    strikeHistoryRef.current = recent;
    if (recent.length >= MAX_STRIKES_PER_MINUTE) return;
    strikeHistoryRef.current.push(now);

    const canvas = canvasRef.current;
    if (!canvas) return;
    const w = canvas.clientWidth;
    const h = canvas.clientHeight;
    if (w === 0 || h === 0) return;

    // Origin + target placement.
    // Distant: top edge, anywhere across 70% of width, target also high
    // (so the bolt doesn't reach far into the visible area).
    // Close: upper third, target deep into the visible area.
    let originX: number, originY: number, targetX: number, targetY: number;
    if (distance === "distant") {
      // Pick a side band: -10% to 20% or 80% to 110% of width — feels
      // off-screen-y.
      const left = Math.random() < 0.5;
      originX = left ? -w * 0.1 + Math.random() * w * 0.3 : w * 0.8 + Math.random() * w * 0.3;
      originY = -h * 0.05 + Math.random() * h * 0.18;
      targetX = originX + (Math.random() * 2 - 1) * w * 0.18;
      targetY = h * 0.18 + Math.random() * h * 0.18;
    } else {
      originX = w * 0.15 + Math.random() * w * 0.7;
      originY = -h * 0.05 + Math.random() * h * 0.15;
      targetX = originX + (Math.random() * 2 - 1) * w * 0.22;
      targetY = h * 0.55 + Math.random() * h * 0.3;
    }

    const seed = Math.floor(Math.random() * 1e9);

    // Build the strokes — leader, return, 1-3 subsequents.
    const strokes: Stroke[] = [];
    let offset = 0;

    // Leader — faint, jagged.
    const leaderGeom = generateBolt({
      originX, originY, targetX, targetY,
      seed, depth: 6, displacementFactor: 0.32,
    });
    strokes.push({
      segments: leaderGeom,
      startOffsetMs: 0,
      durationMs: distance === "close" ? 80 : 100,
      peakAlpha: 0.32,
      isReturnStroke: false,
    });
    offset += 50; // leader-to-return gap

    // Return stroke — bright, primary.
    const returnGeom = generateBolt({
      originX, originY, targetX, targetY,
      seed: seed + 1, depth: 6, displacementFactor: 0.26,
    });
    strokes.push({
      segments: returnGeom,
      startOffsetMs: offset,
      durationMs: distance === "close" ? 50 : 60,
      peakAlpha: 0.96,
      isReturnStroke: true,
    });
    offset += 60;

    // Subsequents — 1-3 more.
    const subCount = 1 + Math.floor(Math.random() * 3);
    for (let i = 0; i < subCount; i++) {
      const subGeom = generateSubsequentStroke(
        { originX, originY, targetX, targetY, seed },
        i + 2,
      );
      strokes.push({
        segments: subGeom,
        startOffsetMs: offset,
        durationMs: 60 + Math.random() * 40,
        peakAlpha: 0.68 - i * 0.12,
        isReturnStroke: false,
      });
      offset += 70;
    }

    const strike: Strike = {
      strokes,
      startMs: performance.now(),
      distance,
      illuminationFired: false,
      thunderFired: false,
      originX, originY, targetX, targetY,
      seed,
      tint: strikeTint,
    };
    strikesRef.current.push(strike);

    // Schedule thunder.
    if (!mute) {
      try {
        playThunder({ distance });
      } catch {
        // Best-effort: audio failures don't block the visual.
      }
      strike.thunderFired = true;
    }
  }

  return (
    <div
      data-testid="lightning-root"
      style={{ position: "absolute", inset: 0, pointerEvents: "none", overflow: "hidden" }}
    >
      <canvas
        ref={canvasRef}
        style={{
          position: "absolute",
          inset: 0,
          width: "100%",
          height: "100%",
          mixBlendMode: "screen",
        }}
      />
      {/* Full-scene illumination overlay — the "lightning fills the room" moment.
          Kept at white-with-blue-tint so it reads as cool plasma light, not
          a flashbang. */}
      <div
        ref={flashOverlayRef}
        aria-hidden="true"
        style={{
          position: "absolute",
          inset: 0,
          background: "rgba(208, 232, 255, 1)",
          opacity: 0,
          mixBlendMode: "screen",
          pointerEvents: "none",
          transition: "none",
        }}
      />
    </div>
  );
}

// ─── Canvas drawing helpers ──────────────────────────────────────────────

function drawStroke(
  ctx: CanvasRenderingContext2D,
  stroke: Stroke,
  alpha: number,
  themeAccent: string,
  distance: "distant" | "close",
  strikeTint?: string,
): void {
  if (alpha <= 0) return;

  // Bolt width scales with distance — close strikes are thicker.
  const baseWidth = distance === "close" ? 3.0 : 1.8;

  // When a per-strike tint is set (lock-in ceremony for a specific player),
  // the halo and afterglow shift to that player's color so the strike reads
  // as THEIRS. The hot white core stays white — real lightning plasma is
  // white regardless of the surrounding storm color.
  const haloColor = strikeTint ? hexToRgba(strikeTint, 0.4) : OUTER_HALO_COLOR;
  const afterglowColor = strikeTint ?? themeAccent;

  // Three passes per stroke for the color layering:
  //   1. Outer halo  — wide, tinted or default purple, low alpha
  //   2. Inner glow  — mid, blue-white, med alpha (unchanged — keeps the
  //                    plasma feel even when the halo is a custom color)
  //   3. Core        — thin, pure white, high alpha (never tinted)
  // Composited via screen blend (set on the canvas style), each layer
  // adding to the others.

  // Halo.
  ctx.save();
  ctx.strokeStyle = haloColor;
  ctx.globalAlpha = alpha * 0.6;
  ctx.lineCap = "round";
  ctx.lineJoin = "round";
  ctx.shadowColor = haloColor;
  ctx.shadowBlur = baseWidth * 8;
  drawSegments(ctx, stroke.segments, baseWidth * 3.5);
  ctx.restore();

  // Inner glow.
  ctx.save();
  ctx.strokeStyle = INNER_GLOW_COLOR;
  ctx.globalAlpha = alpha * 0.85;
  ctx.lineCap = "round";
  ctx.lineJoin = "round";
  ctx.shadowColor = INNER_GLOW_COLOR;
  ctx.shadowBlur = baseWidth * 4;
  drawSegments(ctx, stroke.segments, baseWidth * 1.7);
  ctx.restore();

  // Core — always white, never tinted.
  ctx.save();
  ctx.strokeStyle = CORE_COLOR;
  ctx.globalAlpha = alpha;
  ctx.lineCap = "round";
  ctx.lineJoin = "round";
  drawSegments(ctx, stroke.segments, baseWidth);
  ctx.restore();

  // Tail afterglow — kept very subtle. Uses the tint color when set so the
  // player's color lingers as the strike fades out.
  if (alpha < 0.18) {
    ctx.save();
    ctx.strokeStyle = hexToRgba(afterglowColor, alpha * 0.5);
    ctx.globalAlpha = 1;
    ctx.lineCap = "round";
    ctx.lineJoin = "round";
    ctx.shadowColor = hexToRgba(afterglowColor, 0.4);
    ctx.shadowBlur = baseWidth * 5;
    drawSegments(ctx, stroke.segments, baseWidth * 1.2);
    ctx.restore();
  }
}

function drawSegments(
  ctx: CanvasRenderingContext2D,
  segments: BoltSegment[],
  baseLineWidth: number,
): void {
  ctx.beginPath();
  for (const seg of segments) {
    ctx.lineWidth = baseLineWidth * seg.thickness;
    ctx.moveTo(seg.x1, seg.y1);
    ctx.lineTo(seg.x2, seg.y2);
  }
  ctx.stroke();
}

function hexToRgba(hex: string, alpha: number): string {
  const cleaned = hex.replace(/^#/, "");
  if (cleaned.length !== 6) return `rgba(232, 196, 106, ${alpha})`;
  const r = parseInt(cleaned.slice(0, 2), 16);
  const g = parseInt(cleaned.slice(2, 4), 16);
  const b = parseInt(cleaned.slice(4, 6), 16);
  if ([r, g, b].some(Number.isNaN)) return `rgba(232, 196, 106, ${alpha})`;
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
}

// ─── Legacy fallback (reduced motion) ────────────────────────────────────
// Same two-radial-gradient pattern that used to live as `LightningFlicker`
// in Weather.tsx. Reduced-motion users get the soft glow instead of the
// procedural strikes (the multi-stage flash is a seizure risk for some,
// and the existing globals.css `prefers-reduced-motion` block already
// pauses the underlying CSS keyframes anyway).

function LegacyFlicker({ color = "#E8C46A" }: { color?: string }) {
  return (
    <div
      data-testid="lightning-legacy-flicker"
      style={{ position: "absolute", inset: 0, pointerEvents: "none", overflow: "hidden" }}
    >
      <div
        style={{
          position: "absolute",
          inset: 0,
          background: `radial-gradient(60% 40% at 70% 0%, ${color}, transparent 60%)`,
          mixBlendMode: "screen",
          animation: "tr1via-lightning 11s infinite",
        }}
      />
      <div
        style={{
          position: "absolute",
          inset: 0,
          background: `radial-gradient(40% 30% at 20% 10%, ${color}99, transparent 70%)`,
          mixBlendMode: "screen",
          animation: "tr1via-lightning 13.7s infinite 3.4s",
        }}
      />
    </div>
  );
}

// Re-export for sites that need to know the constant exists (e.g., dev
// tools showing rate ceilings).
export const LIGHTNING_MAX_STRIKES_PER_MINUTE = MAX_STRIKES_PER_MINUTE;
export const LIGHTNING_SCENE_FLASH_PEAK_ALPHA = SCENE_FLASH_PEAK_ALPHA;
