// Generated by `supabase gen types typescript` against the live Trivia
// project (ref citweuctcnuxmqjxcbiz). Do not hand-edit the generated
// portion. To regenerate:
//   npm run typegen
// (which calls `supabase gen types typescript --local --schema public`).
// Or run via MCP: mcp__plugin_supabase_supabase__generate_typescript_types.
//
// The convenience aliases at the bottom (HostRow, NightRow, etc.) ARE
// hand-maintained — they narrow JSONB / state fields beyond what the
// generator can express. Keep them in sync with the generated shapes.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      adjustments: {
        Row: {
          created_at: string
          delta: number
          game_id: string
          id: string
          player_id: string
          reason: string | null
        }
        Insert: {
          created_at?: string
          delta: number
          game_id: string
          id?: string
          player_id: string
          reason?: string | null
        }
        Update: {
          created_at?: string
          delta?: number
          game_id?: string
          id?: string
          player_id?: string
          reason?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "adjustments_game_id_fkey"
            columns: ["game_id"]
            isOneToOne: false
            referencedRelation: "games"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "adjustments_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "game_scores"
            referencedColumns: ["player_id"]
          },
          {
            foreignKeyName: "adjustments_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "players"
            referencedColumns: ["id"]
          },
        ]
      }
      answers: {
        Row: {
          awarded_points: number | null
          chosen_index: number
          id: string
          is_correct: boolean | null
          locked_at: string
          ms_to_lock: number
          player_id: string
          question_id: string
          scramble: Json
        }
        Insert: {
          awarded_points?: number | null
          chosen_index: number
          id?: string
          is_correct?: boolean | null
          locked_at?: string
          ms_to_lock: number
          player_id: string
          question_id: string
          scramble: Json
        }
        Update: {
          awarded_points?: number | null
          chosen_index?: number
          id?: string
          is_correct?: boolean | null
          locked_at?: string
          ms_to_lock?: number
          player_id?: string
          question_id?: string
          scramble?: Json
        }
        Relationships: [
          {
            foreignKeyName: "answers_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "game_scores"
            referencedColumns: ["player_id"]
          },
          {
            foreignKeyName: "answers_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "players"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "answers_question_id_fkey"
            columns: ["question_id"]
            isOneToOne: false
            referencedRelation: "questions"
            referencedColumns: ["id"]
          },
        ]
      }
      audience_topic_votes: {
        Row: {
          id: string
          night_id: string
          player_id: string
          topic: string
          voted_at: string
        }
        Insert: {
          id?: string
          night_id: string
          player_id: string
          topic: string
          voted_at?: string
        }
        Update: {
          id?: string
          night_id?: string
          player_id?: string
          topic?: string
          voted_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "audience_topic_votes_night_id_fkey"
            columns: ["night_id"]
            isOneToOne: false
            referencedRelation: "nights"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "audience_topic_votes_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "game_scores"
            referencedColumns: ["player_id"]
          },
          {
            foreignKeyName: "audience_topic_votes_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "players"
            referencedColumns: ["id"]
          },
        ]
      }
      categories: {
        Row: {
          color: string | null
          created_at: string
          flavor: Json | null
          game_id: string
          id: string
          name: string
          position: number
          state: string
          topic: string
        }
        Insert: {
          color?: string | null
          created_at?: string
          flavor?: Json | null
          game_id: string
          id?: string
          name: string
          position: number
          state?: string
          topic: string
        }
        Update: {
          color?: string | null
          created_at?: string
          flavor?: Json | null
          game_id?: string
          id?: string
          name?: string
          position?: number
          state?: string
          topic?: string
        }
        Relationships: [
          {
            foreignKeyName: "categories_game_id_fkey"
            columns: ["game_id"]
            isOneToOne: false
            referencedRelation: "games"
            referencedColumns: ["id"]
          },
        ]
      }
      game_participations: {
        Row: {
          game_id: string
          id: string
          joined_at: string
          player_id: string
        }
        Insert: {
          game_id: string
          id?: string
          joined_at?: string
          player_id: string
        }
        Update: {
          game_id?: string
          id?: string
          joined_at?: string
          player_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "game_participations_game_id_fkey"
            columns: ["game_id"]
            isOneToOne: false
            referencedRelation: "games"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "game_participations_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "game_scores"
            referencedColumns: ["player_id"]
          },
          {
            foreignKeyName: "game_participations_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "players"
            referencedColumns: ["id"]
          },
        ]
      }
      games: {
        Row: {
          category_count: number
          ended_at: string | null
          game_no: number
          id: string
          night_id: string
          question_count: number
          started_at: string | null
          state: string
        }
        Insert: {
          category_count?: number
          ended_at?: string | null
          game_no: number
          id?: string
          night_id: string
          question_count?: number
          started_at?: string | null
          state?: string
        }
        Update: {
          category_count?: number
          ended_at?: string | null
          game_no?: number
          id?: string
          night_id?: string
          question_count?: number
          started_at?: string | null
          state?: string
        }
        Relationships: [
          {
            foreignKeyName: "games_night_id_fkey"
            columns: ["night_id"]
            isOneToOne: false
            referencedRelation: "nights"
            referencedColumns: ["id"]
          },
        ]
      }
      hosts: {
        Row: {
          comped_at: string | null
          comped_by: string | null
          created_at: string
          default_theme_key: string
          default_venue: string | null
          display_name: string
          id: string
          is_first_night_complete: boolean
          is_paywall_bypassed: boolean
          role: string
          current_period_end: string | null
          stripe_customer_id: string | null
          stripe_subscription_id: string | null
          subscription_status: string | null
          trial_ends_at: string | null
          user_id: string
        }
        Insert: {
          comped_at?: string | null
          comped_by?: string | null
          created_at?: string
          default_theme_key?: string
          default_venue?: string | null
          display_name: string
          id?: string
          is_first_night_complete?: boolean
          is_paywall_bypassed?: boolean
          role?: string
          current_period_end?: string | null
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          subscription_status?: string | null
          trial_ends_at?: string | null
          user_id: string
        }
        Update: {
          comped_at?: string | null
          comped_by?: string | null
          created_at?: string
          default_theme_key?: string
          default_venue?: string | null
          display_name?: string
          id?: string
          is_first_night_complete?: boolean
          is_paywall_bypassed?: boolean
          role?: string
          current_period_end?: string | null
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          subscription_status?: string | null
          trial_ends_at?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "hosts_comped_by_fkey"
            columns: ["comped_by"]
            isOneToOne: false
            referencedRelation: "hosts"
            referencedColumns: ["id"]
          },
        ]
      }
      nights: {
        Row: {
          closed_at: string | null
          created_at: string
          host_id: string
          id: string
          is_locked: boolean
          opened_at: string | null
          room_code: string
          scheduled_at: string | null
          theme_key: string | null
          venue_name: string
        }
        Insert: {
          closed_at?: string | null
          created_at?: string
          host_id: string
          id?: string
          is_locked?: boolean
          opened_at?: string | null
          room_code: string
          scheduled_at?: string | null
          theme_key?: string | null
          venue_name: string
        }
        Update: {
          closed_at?: string | null
          created_at?: string
          host_id?: string
          id?: string
          is_locked?: boolean
          opened_at?: string | null
          room_code?: string
          scheduled_at?: string | null
          theme_key?: string | null
          venue_name?: string
        }
        Relationships: [
          {
            foreignKeyName: "nights_host_id_fkey"
            columns: ["host_id"]
            isOneToOne: false
            referencedRelation: "hosts"
            referencedColumns: ["id"]
          },
        ]
      }
      players: {
        Row: {
          app_switch_total_seconds: number
          device_id: string
          display_name: string
          id: string
          joined_at: string
          last_seen_at: string
          night_id: string
          removed_at: string | null
        }
        Insert: {
          app_switch_total_seconds?: number
          device_id: string
          display_name: string
          id?: string
          joined_at?: string
          last_seen_at?: string
          night_id: string
          removed_at?: string | null
        }
        Update: {
          app_switch_total_seconds?: number
          device_id?: string
          display_name?: string
          id?: string
          joined_at?: string
          last_seen_at?: string
          night_id?: string
          removed_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "players_night_id_fkey"
            columns: ["night_id"]
            isOneToOne: false
            referencedRelation: "nights"
            referencedColumns: ["id"]
          },
        ]
      }
      questions: {
        Row: {
          category_id: string
          correct_index: number
          difficulty: number
          fact_blurb: string | null
          finished_at: string | null
          id: string
          image_attribution: string | null
          image_source: string | null
          image_url: string | null
          is_picked: boolean
          options: Json
          played_at: string | null
          point_value: number | null
          prompt: string
          source: string
        }
        Insert: {
          category_id: string
          correct_index: number
          difficulty?: number
          fact_blurb?: string | null
          finished_at?: string | null
          id?: string
          image_attribution?: string | null
          image_source?: string | null
          image_url?: string | null
          is_picked?: boolean
          options: Json
          played_at?: string | null
          point_value?: number | null
          prompt: string
          source?: string
        }
        Update: {
          category_id?: string
          correct_index?: number
          difficulty?: number
          fact_blurb?: string | null
          finished_at?: string | null
          id?: string
          image_attribution?: string | null
          image_source?: string | null
          image_url?: string | null
          is_picked?: boolean
          options?: Json
          played_at?: string | null
          point_value?: number | null
          prompt?: string
          source?: string
        }
        Relationships: [
          {
            foreignKeyName: "questions_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["id"]
          },
        ]
      }
      reveals: {
        Row: {
          event: string
          game_id: string
          id: string
          metadata: Json | null
          occurred_at: string
          question_id: string
        }
        Insert: {
          event: string
          game_id: string
          id?: string
          metadata?: Json | null
          occurred_at?: string
          question_id: string
        }
        Update: {
          event?: string
          game_id?: string
          id?: string
          metadata?: Json | null
          occurred_at?: string
          question_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "reveals_game_id_fkey"
            columns: ["game_id"]
            isOneToOne: false
            referencedRelation: "games"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reveals_question_id_fkey"
            columns: ["question_id"]
            isOneToOne: false
            referencedRelation: "questions"
            referencedColumns: ["id"]
          },
        ]
      }
      topic_suggestions: {
        Row: {
          created_at: string
          id: string
          player_id: string
          text: string
        }
        Insert: {
          created_at?: string
          id?: string
          player_id: string
          text: string
        }
        Update: {
          created_at?: string
          id?: string
          player_id?: string
          text?: string
        }
        Relationships: [
          {
            foreignKeyName: "topic_suggestions_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "game_scores"
            referencedColumns: ["player_id"]
          },
          {
            foreignKeyName: "topic_suggestions_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "players"
            referencedColumns: ["id"]
          },
        ]
      }
      venues: {
        Row: {
          brand_color: string | null
          created_at: string
          host_id: string
          id: string
          name: string
        }
        Insert: {
          brand_color?: string | null
          created_at?: string
          host_id: string
          id?: string
          name: string
        }
        Update: {
          brand_color?: string | null
          created_at?: string
          host_id?: string
          id?: string
          name?: string
        }
        Relationships: [
          {
            foreignKeyName: "venues_host_id_fkey"
            columns: ["host_id"]
            isOneToOne: false
            referencedRelation: "hosts"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      game_scores: {
        Row: {
          answered_count: number | null
          correct_count: number | null
          display_name: string | null
          fastest_correct_ms: number | null
          game_id: string | null
          player_id: string | null
          score: number | null
        }
        Relationships: [
          {
            foreignKeyName: "game_participations_game_id_fkey"
            columns: ["game_id"]
            isOneToOne: false
            referencedRelation: "games"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Functions: {
      current_device_id: { Args: never; Returns: string }
      current_player_id: { Args: { p_night_id: string }; Returns: string }
      is_night_host: { Args: { p_night_id: string }; Returns: boolean }
      reset_night_to_setup: { Args: { p_night_id: string }; Returns: Json }
      resolve_question: { Args: { p_question_id: string }; Returns: undefined }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const

// ─────────────────────────────────────────────────────────────────────────
// Convenience aliases. The codebase imports `HostRow`, `NightInsert`, etc.
// directly. These map to the same shapes as Tables<'hosts'>, TablesInsert<...>,
// etc. — kept here so callers don't need to know the helper-generic form.
// JSONB / state fields are narrowed beyond what Postgres can express.
// ─────────────────────────────────────────────────────────────────────────

/** role is constrained to 'host' | 'founder' by a CHECK constraint. */
export type HostRole = "host" | "founder"

export type HostRow = Omit<Tables<"hosts">, "role"> & { role: HostRole }
export type HostInsert = Omit<TablesInsert<"hosts">, "role"> & { role?: HostRole }
export type HostUpdate = Omit<TablesUpdate<"hosts">, "role"> & { role?: HostRole }

export type VenueRow           = Tables<"venues">
export type VenueInsert        = TablesInsert<"venues">
export type VenueUpdate        = TablesUpdate<"venues">

export type NightRow           = Tables<"nights">
export type NightInsert        = TablesInsert<"nights">
export type NightUpdate        = TablesUpdate<"nights">

/** game_no is constrained 1-2 in SQL; narrow here to surface that to TS. */
export type GameRow = Omit<Tables<"games">, "game_no" | "state"> & {
  game_no: 1 | 2
  state: "draft" | "ready" | "live" | "done"
}
export type GameInsert = Omit<TablesInsert<"games">, "game_no" | "state"> & {
  game_no: 1 | 2
  state?: "draft" | "ready" | "live" | "done"
}
export type GameUpdate = Omit<TablesUpdate<"games">, "game_no" | "state"> & {
  game_no?: 1 | 2
  state?: "draft" | "ready" | "live" | "done"
}

export type CategoryRow = Omit<Tables<"categories">, "state"> & {
  state: "draft" | "generating" | "review" | "ready"
}
export type CategoryInsert = Omit<TablesInsert<"categories">, "state"> & {
  state?: "draft" | "generating" | "review" | "ready"
}
export type CategoryUpdate = Omit<TablesUpdate<"categories">, "state"> & {
  state?: "draft" | "generating" | "review" | "ready"
}

/** A question option set is always a 4-element string tuple; correct_index
 *  is always 0-3. We store them in JSONB / smallint for flexibility, but
 *  the app's invariants are tighter — narrow here so callers don't need to
 *  validate every read. Writes go through Zod at the API boundary which
 *  enforces these same shapes. */
export type QuestionRow = Omit<Tables<"questions">, "options" | "correct_index" | "point_value"> & {
  options: [string, string, string, string]
  correct_index: 0 | 1 | 2 | 3
  point_value: 100 | 200 | 300 | 400 | 500 | 600 | 700 | null
}
export type QuestionInsert = Omit<TablesInsert<"questions">, "options" | "correct_index" | "point_value"> & {
  options: [string, string, string, string]
  correct_index: 0 | 1 | 2 | 3
  point_value?: 100 | 200 | 300 | 400 | 500 | 600 | 700 | null
}
export type QuestionUpdate = Omit<TablesUpdate<"questions">, "options" | "correct_index" | "point_value"> & {
  options?: [string, string, string, string]
  correct_index?: 0 | 1 | 2 | 3
  point_value?: 100 | 200 | 300 | 400 | 500 | 600 | 700 | null
}

export type PlayerRow          = Tables<"players">
export type PlayerInsert       = TablesInsert<"players">
export type PlayerUpdate       = TablesUpdate<"players">

export type ParticipationRow   = Tables<"game_participations">
export type ParticipationInsert = TablesInsert<"game_participations">
export type ParticipationUpdate = TablesUpdate<"game_participations">

/** scramble is always a 4-element permutation of [0,1,2,3]; chosen_index
 *  is always 0-3. Enforced server-side by lib/game/scramble.ts. */
export type AnswerRow = Omit<Tables<"answers">, "scramble" | "chosen_index"> & {
  scramble: [number, number, number, number]
  chosen_index: 0 | 1 | 2 | 3
}
export type AnswerInsert = Omit<TablesInsert<"answers">, "scramble" | "chosen_index"> & {
  scramble: [number, number, number, number]
  chosen_index: 0 | 1 | 2 | 3
}
export type AnswerUpdate = Omit<TablesUpdate<"answers">, "scramble" | "chosen_index"> & {
  scramble?: [number, number, number, number]
  chosen_index?: 0 | 1 | 2 | 3
}

export type RevealRow = Omit<Tables<"reveals">, "event"> & {
  event: "reveal" | "undo" | "end-early" | "resolve"
}
export type RevealInsert = Omit<TablesInsert<"reveals">, "event"> & {
  event: "reveal" | "undo" | "end-early" | "resolve"
}
export type RevealUpdate = Omit<TablesUpdate<"reveals">, "event"> & {
  event?: "reveal" | "undo" | "end-early" | "resolve"
}

export type AdjustmentRow      = Tables<"adjustments">
export type AdjustmentInsert   = TablesInsert<"adjustments">
export type AdjustmentUpdate   = TablesUpdate<"adjustments">

export type TopicSuggestionRow    = Tables<"topic_suggestions">
export type TopicSuggestionInsert = TablesInsert<"topic_suggestions">
export type TopicSuggestionUpdate = TablesUpdate<"topic_suggestions">

export type AudienceTopicVoteRow    = Tables<"audience_topic_votes">
export type AudienceTopicVoteInsert = TablesInsert<"audience_topic_votes">
export type AudienceTopicVoteUpdate = TablesUpdate<"audience_topic_votes">

/** View row — game_scores. Columns are nullable because of the underlying
 *  LEFT JOIN; the app filters out rows where player_id is null. */
export type GameScoreRow       = Tables<"game_scores">
