// Generated by `supabase gen types typescript --local --schema public`.
// Do not hand-edit the generated portion. The convenience aliases at the
// bottom are intentionally maintained by the application.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      adjustments: {
        Row: {
          created_at: string
          delta: number
          game_id: string
          id: string
          player_id: string
          reason: string | null
        }
        Insert: {
          created_at?: string
          delta: number
          game_id: string
          id?: string
          player_id: string
          reason?: string | null
        }
        Update: {
          created_at?: string
          delta?: number
          game_id?: string
          id?: string
          player_id?: string
          reason?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "adjustments_game_id_fkey"
            columns: ["game_id"]
            isOneToOne: false
            referencedRelation: "games"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "adjustments_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "game_scores"
            referencedColumns: ["player_id"]
          },
          {
            foreignKeyName: "adjustments_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "players"
            referencedColumns: ["id"]
          },
        ]
      }
      answers: {
        Row: {
          awarded_points: number | null
          chosen_index: number
          id: string
          is_correct: boolean | null
          locked_at: string
          ms_to_lock: number
          player_id: string
          question_id: string
          scramble: Json
        }
        Insert: {
          awarded_points?: number | null
          chosen_index: number
          id?: string
          is_correct?: boolean | null
          locked_at?: string
          ms_to_lock: number
          player_id: string
          question_id: string
          scramble: Json
        }
        Update: {
          awarded_points?: number | null
          chosen_index?: number
          id?: string
          is_correct?: boolean | null
          locked_at?: string
          ms_to_lock?: number
          player_id?: string
          question_id?: string
          scramble?: Json
        }
        Relationships: [
          {
            foreignKeyName: "answers_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "game_scores"
            referencedColumns: ["player_id"]
          },
          {
            foreignKeyName: "answers_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "players"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "answers_question_id_fkey"
            columns: ["question_id"]
            isOneToOne: false
            referencedRelation: "questions"
            referencedColumns: ["id"]
          },
        ]
      }
      audience_topic_votes: {
        Row: {
          id: string
          night_id: string
          player_id: string
          topic: string
          voted_at: string
        }
        Insert: {
          id?: string
          night_id: string
          player_id: string
          topic: string
          voted_at?: string
        }
        Update: {
          id?: string
          night_id?: string
          player_id?: string
          topic?: string
          voted_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "audience_topic_votes_night_id_fkey"
            columns: ["night_id"]
            isOneToOne: false
            referencedRelation: "nights"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "audience_topic_votes_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "game_scores"
            referencedColumns: ["player_id"]
          },
          {
            foreignKeyName: "audience_topic_votes_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "players"
            referencedColumns: ["id"]
          },
        ]
      }
      categories: {
        Row: {
          color: string | null
          created_at: string
          flavor: Json | null
          game_id: string
          id: string
          name: string
          position: number
          state: string
          topic: string
        }
        Insert: {
          color?: string | null
          created_at?: string
          flavor?: Json | null
          game_id: string
          id?: string
          name: string
          position: number
          state?: string
          topic: string
        }
        Update: {
          color?: string | null
          created_at?: string
          flavor?: Json | null
          game_id?: string
          id?: string
          name?: string
          position?: number
          state?: string
          topic?: string
        }
        Relationships: [
          {
            foreignKeyName: "categories_game_id_fkey"
            columns: ["game_id"]
            isOneToOne: false
            referencedRelation: "games"
            referencedColumns: ["id"]
          },
        ]
      }
      game_participations: {
        Row: {
          game_id: string
          id: string
          joined_at: string
          player_id: string
        }
        Insert: {
          game_id: string
          id?: string
          joined_at?: string
          player_id: string
        }
        Update: {
          game_id?: string
          id?: string
          joined_at?: string
          player_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "game_participations_game_id_fkey"
            columns: ["game_id"]
            isOneToOne: false
            referencedRelation: "games"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "game_participations_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "game_scores"
            referencedColumns: ["player_id"]
          },
          {
            foreignKeyName: "game_participations_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "players"
            referencedColumns: ["id"]
          },
        ]
      }
      games: {
        Row: {
          category_count: number
          ended_at: string | null
          game_no: number
          id: string
          night_id: string
          question_count: number
          started_at: string | null
          state: string
        }
        Insert: {
          category_count?: number
          ended_at?: string | null
          game_no: number
          id?: string
          night_id: string
          question_count?: number
          started_at?: string | null
          state?: string
        }
        Update: {
          category_count?: number
          ended_at?: string | null
          game_no?: number
          id?: string
          night_id?: string
          question_count?: number
          started_at?: string | null
          state?: string
        }
        Relationships: [
          {
            foreignKeyName: "games_night_id_fkey"
            columns: ["night_id"]
            isOneToOne: false
            referencedRelation: "nights"
            referencedColumns: ["id"]
          },
        ]
      }
      host_answer_engine_settings: {
        Row: {
          host_id: string
          preferred_engine: string
          release_enabled: boolean
          updated_at: string
        }
        Insert: {
          host_id: string
          preferred_engine?: string
          release_enabled?: boolean
          updated_at?: string
        }
        Update: {
          host_id?: string
          preferred_engine?: string
          release_enabled?: boolean
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "host_answer_engine_settings_host_id_fkey"
            columns: ["host_id"]
            isOneToOne: true
            referencedRelation: "hosts"
            referencedColumns: ["id"]
          },
        ]
      }
      hosts: {
        Row: {
          comped_at: string | null
          comped_by: string | null
          created_at: string
          current_period_end: string | null
          default_theme_key: string
          default_venue: string | null
          display_name: string
          id: string
          is_first_night_complete: boolean
          is_paywall_bypassed: boolean
          role: string
          stripe_customer_id: string | null
          stripe_subscription_id: string | null
          subscription_status: string | null
          trial_ends_at: string | null
          user_id: string
        }
        Insert: {
          comped_at?: string | null
          comped_by?: string | null
          created_at?: string
          current_period_end?: string | null
          default_theme_key?: string
          default_venue?: string | null
          display_name: string
          id?: string
          is_first_night_complete?: boolean
          is_paywall_bypassed?: boolean
          role?: string
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          subscription_status?: string | null
          trial_ends_at?: string | null
          user_id: string
        }
        Update: {
          comped_at?: string | null
          comped_by?: string | null
          created_at?: string
          current_period_end?: string | null
          default_theme_key?: string
          default_venue?: string | null
          display_name?: string
          id?: string
          is_first_night_complete?: boolean
          is_paywall_bypassed?: boolean
          role?: string
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          subscription_status?: string | null
          trial_ends_at?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "hosts_comped_by_fkey"
            columns: ["comped_by"]
            isOneToOne: false
            referencedRelation: "hosts"
            referencedColumns: ["id"]
          },
        ]
      }
      live_command_receipt_archive: {
        Row: {
          archived_at: string
          canonical_result: Json
          command_id: string
          completed_at: string
          created_at: string
          expected_control_revision: number
          expected_game_id: string | null
          expected_play_id: string | null
          expected_play_status: string | null
          kind: string
          night_id: string
          request_hash: string
          run_id: string | null
          status: string
        }
        Insert: {
          archived_at?: string
          canonical_result: Json
          command_id: string
          completed_at: string
          created_at: string
          expected_control_revision: number
          expected_game_id?: string | null
          expected_play_id?: string | null
          expected_play_status?: string | null
          kind: string
          night_id: string
          request_hash: string
          run_id?: string | null
          status: string
        }
        Update: {
          archived_at?: string
          canonical_result?: Json
          command_id?: string
          completed_at?: string
          created_at?: string
          expected_control_revision?: number
          expected_game_id?: string | null
          expected_play_id?: string | null
          expected_play_status?: string | null
          kind?: string
          night_id?: string
          request_hash?: string
          run_id?: string | null
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "live_command_receipt_archive_night_id_fkey"
            columns: ["night_id"]
            isOneToOne: false
            referencedRelation: "nights"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "live_command_receipt_archive_run_fk"
            columns: ["night_id", "run_id"]
            isOneToOne: false
            referencedRelation: "live_night_runs"
            referencedColumns: ["night_id", "run_id"]
          },
        ]
      }
      live_command_receipts: {
        Row: {
          canonical_result: Json | null
          command_id: string
          completed_at: string | null
          created_at: string
          expected_control_revision: number
          expected_game_id: string | null
          expected_play_id: string | null
          expected_play_status: string | null
          kind: string
          night_id: string
          request_hash: string
          run_id: string | null
          status: string
        }
        Insert: {
          canonical_result?: Json | null
          command_id: string
          completed_at?: string | null
          created_at?: string
          expected_control_revision: number
          expected_game_id?: string | null
          expected_play_id?: string | null
          expected_play_status?: string | null
          kind: string
          night_id: string
          request_hash: string
          run_id?: string | null
          status?: string
        }
        Update: {
          canonical_result?: Json | null
          command_id?: string
          completed_at?: string | null
          created_at?: string
          expected_control_revision?: number
          expected_game_id?: string | null
          expected_play_id?: string | null
          expected_play_status?: string | null
          kind?: string
          night_id?: string
          request_hash?: string
          run_id?: string | null
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "live_command_receipts_game_night_fk"
            columns: ["expected_game_id", "night_id"]
            isOneToOne: false
            referencedRelation: "games"
            referencedColumns: ["id", "night_id"]
          },
          {
            foreignKeyName: "live_command_receipts_night_fk"
            columns: ["night_id"]
            isOneToOne: false
            referencedRelation: "nights"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "live_command_receipts_night_run_fk"
            columns: ["night_id", "run_id"]
            isOneToOne: false
            referencedRelation: "live_night_runs"
            referencedColumns: ["night_id", "run_id"]
          },
          {
            foreignKeyName: "live_command_receipts_play_ancestry_fk"
            columns: [
              "expected_play_id",
              "night_id",
              "run_id",
              "expected_game_id",
            ]
            isOneToOne: false
            referencedRelation: "question_plays"
            referencedColumns: ["id", "night_id", "run_id", "game_id"]
          },
        ]
      }
      live_night_runs: {
        Row: {
          answer_engine: string
          ended_at: string | null
          night_id: string
          run_id: string
          started_at: string
        }
        Insert: {
          answer_engine: string
          ended_at?: string | null
          night_id: string
          run_id: string
          started_at?: string
        }
        Update: {
          answer_engine?: string
          ended_at?: string | null
          night_id?: string
          run_id?: string
          started_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "live_night_runs_night_id_fkey"
            columns: ["night_id"]
            isOneToOne: false
            referencedRelation: "nights"
            referencedColumns: ["id"]
          },
        ]
      }
      live_room_events: {
        Row: {
          control_revision: number
          created_at: string
          game_id: string | null
          id: string
          kind: string
          night_id: string
          payload: Json
          play_id: string | null
          question_id: string | null
          room_revision: number
          run_id: string
        }
        Insert: {
          control_revision: number
          created_at?: string
          game_id?: string | null
          id?: string
          kind: string
          night_id: string
          payload?: Json
          play_id?: string | null
          question_id?: string | null
          room_revision: number
          run_id: string
        }
        Update: {
          control_revision?: number
          created_at?: string
          game_id?: string | null
          id?: string
          kind?: string
          night_id?: string
          payload?: Json
          play_id?: string | null
          question_id?: string | null
          room_revision?: number
          run_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "live_room_events_game_night_fk"
            columns: ["game_id", "night_id"]
            isOneToOne: false
            referencedRelation: "games"
            referencedColumns: ["id", "night_id"]
          },
          {
            foreignKeyName: "live_room_events_night_run_fk"
            columns: ["night_id", "run_id"]
            isOneToOne: false
            referencedRelation: "nights"
            referencedColumns: ["id", "current_run_id"]
          },
          {
            foreignKeyName: "live_room_events_play_ancestry_fk"
            columns: ["play_id", "night_id", "run_id", "game_id", "question_id"]
            isOneToOne: false
            referencedRelation: "question_plays"
            referencedColumns: [
              "id",
              "night_id",
              "run_id",
              "game_id",
              "question_id",
            ]
          },
        ]
      }
      nights: {
        Row: {
          answer_engine: string
          answer_engine_latched_at: string | null
          closed_at: string | null
          control_revision: number
          created_at: string
          current_run_id: string | null
          host_id: string
          id: string
          is_locked: boolean
          opened_at: string | null
          room_code: string
          room_magic_enabled: boolean
          room_revision: number
          scheduled_at: string | null
          theme_key: string | null
          venue_name: string
        }
        Insert: {
          answer_engine?: string
          answer_engine_latched_at?: string | null
          closed_at?: string | null
          control_revision?: number
          created_at?: string
          current_run_id?: string | null
          host_id: string
          id?: string
          is_locked?: boolean
          opened_at?: string | null
          room_code: string
          room_magic_enabled?: boolean
          room_revision?: number
          scheduled_at?: string | null
          theme_key?: string | null
          venue_name: string
        }
        Update: {
          answer_engine?: string
          answer_engine_latched_at?: string | null
          closed_at?: string | null
          control_revision?: number
          created_at?: string
          current_run_id?: string | null
          host_id?: string
          id?: string
          is_locked?: boolean
          opened_at?: string | null
          room_code?: string
          room_magic_enabled?: boolean
          room_revision?: number
          scheduled_at?: string | null
          theme_key?: string | null
          venue_name?: string
        }
        Relationships: [
          {
            foreignKeyName: "nights_host_id_fkey"
            columns: ["host_id"]
            isOneToOne: false
            referencedRelation: "hosts"
            referencedColumns: ["id"]
          },
        ]
      }
      play_finalize_attempt_windows: {
        Row: {
          attempt_count: number
          play_id: string
          window_started_at: string
        }
        Insert: {
          attempt_count?: number
          play_id: string
          window_started_at: string
        }
        Update: {
          attempt_count?: number
          play_id?: string
          window_started_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "play_finalize_attempt_windows_play_id_fkey"
            columns: ["play_id"]
            isOneToOne: true
            referencedRelation: "question_plays"
            referencedColumns: ["id"]
          },
        ]
      }
      players: {
        Row: {
          app_switch_total_seconds: number
          can_answer: boolean
          device_id: string
          display_name: string
          id: string
          joined_at: string
          last_seen_at: string
          night_id: string
          removed_at: string | null
        }
        Insert: {
          app_switch_total_seconds?: number
          can_answer?: boolean
          device_id: string
          display_name: string
          id?: string
          joined_at?: string
          last_seen_at?: string
          night_id: string
          removed_at?: string | null
        }
        Update: {
          app_switch_total_seconds?: number
          can_answer?: boolean
          device_id?: string
          display_name?: string
          id?: string
          joined_at?: string
          last_seen_at?: string
          night_id?: string
          removed_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "players_night_id_fkey"
            columns: ["night_id"]
            isOneToOne: false
            referencedRelation: "nights"
            referencedColumns: ["id"]
          },
        ]
      }
      question_generation_jobs: {
        Row: {
          attempt: number
          category_id: string
          certified_count: number
          created_at: string
          game_id: string
          heartbeat_at: string
          host_id: string
          id: string
          image_count: number
          last_error: string | null
          night_id: string
          phase: string
          target_count: number
          updated_at: string
          written_count: number
        }
        Insert: {
          attempt?: number
          category_id: string
          certified_count?: number
          created_at?: string
          game_id: string
          heartbeat_at?: string
          host_id: string
          id?: string
          image_count?: number
          last_error?: string | null
          night_id: string
          phase?: string
          target_count?: number
          updated_at?: string
          written_count?: number
        }
        Update: {
          attempt?: number
          category_id?: string
          certified_count?: number
          created_at?: string
          game_id?: string
          heartbeat_at?: string
          host_id?: string
          id?: string
          image_count?: number
          last_error?: string | null
          night_id?: string
          phase?: string
          target_count?: number
          updated_at?: string
          written_count?: number
        }
        Relationships: [
          {
            foreignKeyName: "question_generation_jobs_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: true
            referencedRelation: "categories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "question_generation_jobs_game_id_fkey"
            columns: ["game_id"]
            isOneToOne: false
            referencedRelation: "games"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "question_generation_jobs_host_id_fkey"
            columns: ["host_id"]
            isOneToOne: false
            referencedRelation: "hosts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "question_generation_jobs_night_id_fkey"
            columns: ["night_id"]
            isOneToOne: false
            referencedRelation: "nights"
            referencedColumns: ["id"]
          },
        ]
      }
      question_generation_reports: {
        Row: {
          accepted_count: number
          category_id: string | null
          category_name: string | null
          created_at: string
          estimated_cost_usd: number
          game_id: string | null
          generated_count: number
          host_id: string | null
          id: string
          image_attached_count: number
          image_skipped_count: number
          image_target_count: number
          llm_calls: number
          mode: string
          night_id: string | null
          rejected_count: number
          report: Json
          requested_count: number
          risk_flag_count: number
          rounds: number
          status: string
          tokens_in: number
          tokens_out: number
          topic: string
          verify_passes: number
        }
        Insert: {
          accepted_count: number
          category_id?: string | null
          category_name?: string | null
          created_at?: string
          estimated_cost_usd?: number
          game_id?: string | null
          generated_count: number
          host_id?: string | null
          id?: string
          image_attached_count?: number
          image_skipped_count?: number
          image_target_count?: number
          llm_calls?: number
          mode?: string
          night_id?: string | null
          rejected_count: number
          report?: Json
          requested_count: number
          risk_flag_count?: number
          rounds: number
          status: string
          tokens_in?: number
          tokens_out?: number
          topic: string
          verify_passes: number
        }
        Update: {
          accepted_count?: number
          category_id?: string | null
          category_name?: string | null
          created_at?: string
          estimated_cost_usd?: number
          game_id?: string | null
          generated_count?: number
          host_id?: string | null
          id?: string
          image_attached_count?: number
          image_skipped_count?: number
          image_target_count?: number
          llm_calls?: number
          mode?: string
          night_id?: string | null
          rejected_count?: number
          report?: Json
          requested_count?: number
          risk_flag_count?: number
          rounds?: number
          status?: string
          tokens_in?: number
          tokens_out?: number
          topic?: string
          verify_passes?: number
        }
        Relationships: [
          {
            foreignKeyName: "question_generation_reports_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "question_generation_reports_game_id_fkey"
            columns: ["game_id"]
            isOneToOne: false
            referencedRelation: "games"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "question_generation_reports_host_id_fkey"
            columns: ["host_id"]
            isOneToOne: false
            referencedRelation: "hosts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "question_generation_reports_night_id_fkey"
            columns: ["night_id"]
            isOneToOne: false
            referencedRelation: "nights"
            referencedColumns: ["id"]
          },
        ]
      }
      question_play_answers: {
        Row: {
          awarded_points: number | null
          canonical_index: number
          is_correct: boolean | null
          locked_at: string
          ms_to_lock: number
          play_id: string
          player_id: string
          received_at: string
          submission_id: string
          visible_slot: number
        }
        Insert: {
          awarded_points?: number | null
          canonical_index: number
          is_correct?: boolean | null
          locked_at: string
          ms_to_lock: number
          play_id: string
          player_id: string
          received_at: string
          submission_id: string
          visible_slot: number
        }
        Update: {
          awarded_points?: number | null
          canonical_index?: number
          is_correct?: boolean | null
          locked_at?: string
          ms_to_lock?: number
          play_id?: string
          player_id?: string
          received_at?: string
          submission_id?: string
          visible_slot?: number
        }
        Relationships: [
          {
            foreignKeyName: "question_play_answers_eligible_fk"
            columns: ["play_id", "player_id"]
            isOneToOne: true
            referencedRelation: "question_play_eligibility"
            referencedColumns: ["play_id", "player_id"]
          },
        ]
      }
      question_play_attempt_windows: {
        Row: {
          attempt_count: number
          play_id: string
          player_id: string
          window_started_at: string
        }
        Insert: {
          attempt_count?: number
          play_id: string
          player_id: string
          window_started_at: string
        }
        Update: {
          attempt_count?: number
          play_id?: string
          player_id?: string
          window_started_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "question_play_attempt_windows_eligible_fk"
            columns: ["play_id", "player_id"]
            isOneToOne: true
            referencedRelation: "question_play_eligibility"
            referencedColumns: ["play_id", "player_id"]
          },
        ]
      }
      question_play_eligibility: {
        Row: {
          frozen_at: string
          night_id: string
          play_id: string
          player_id: string
        }
        Insert: {
          frozen_at?: string
          night_id: string
          play_id: string
          player_id: string
        }
        Update: {
          frozen_at?: string
          night_id?: string
          play_id?: string
          player_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "question_play_eligibility_play_night_fk"
            columns: ["play_id", "night_id"]
            isOneToOne: false
            referencedRelation: "question_plays"
            referencedColumns: ["id", "night_id"]
          },
          {
            foreignKeyName: "question_play_eligibility_player_night_fk"
            columns: ["player_id", "night_id"]
            isOneToOne: false
            referencedRelation: "players"
            referencedColumns: ["id", "night_id"]
          },
        ]
      }
      question_plays: {
        Row: {
          category_id: string
          confirmed_count: number
          created_at: string
          eligible_count: number
          final_window_ends_at: string
          final_window_starts_at: string | null
          finalize_at: string | null
          game_id: string
          id: string
          main_zero_at: string
          night_id: string
          opened_at: string
          question_id: string
          resolution_reason: string | null
          resolved_at: string | null
          run_id: string
          status: string
        }
        Insert: {
          category_id: string
          confirmed_count?: number
          created_at?: string
          eligible_count?: number
          final_window_ends_at: string
          final_window_starts_at?: string | null
          finalize_at?: string | null
          game_id: string
          id?: string
          main_zero_at: string
          night_id: string
          opened_at: string
          question_id: string
          resolution_reason?: string | null
          resolved_at?: string | null
          run_id: string
          status?: string
        }
        Update: {
          category_id?: string
          confirmed_count?: number
          created_at?: string
          eligible_count?: number
          final_window_ends_at?: string
          final_window_starts_at?: string | null
          finalize_at?: string | null
          game_id?: string
          id?: string
          main_zero_at?: string
          night_id?: string
          opened_at?: string
          question_id?: string
          resolution_reason?: string | null
          resolved_at?: string | null
          run_id?: string
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "question_plays_category_game_fk"
            columns: ["category_id", "game_id"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["id", "game_id"]
          },
          {
            foreignKeyName: "question_plays_game_night_fk"
            columns: ["game_id", "night_id"]
            isOneToOne: false
            referencedRelation: "games"
            referencedColumns: ["id", "night_id"]
          },
          {
            foreignKeyName: "question_plays_night_run_fk"
            columns: ["night_id", "run_id"]
            isOneToOne: false
            referencedRelation: "nights"
            referencedColumns: ["id", "current_run_id"]
          },
          {
            foreignKeyName: "question_plays_question_category_fk"
            columns: ["question_id", "category_id"]
            isOneToOne: false
            referencedRelation: "questions"
            referencedColumns: ["id", "category_id"]
          },
        ]
      }
      questions: {
        Row: {
          category_id: string
          correct_index: number
          difficulty: number
          fact_blurb: string | null
          finished_at: string | null
          id: string
          image_attribution: string | null
          image_source: string | null
          image_url: string | null
          is_picked: boolean
          options: Json
          played_at: string | null
          point_value: number | null
          prompt: string
          source: string
        }
        Insert: {
          category_id: string
          correct_index: number
          difficulty?: number
          fact_blurb?: string | null
          finished_at?: string | null
          id?: string
          image_attribution?: string | null
          image_source?: string | null
          image_url?: string | null
          is_picked?: boolean
          options: Json
          played_at?: string | null
          point_value?: number | null
          prompt: string
          source?: string
        }
        Update: {
          category_id?: string
          correct_index?: number
          difficulty?: number
          fact_blurb?: string | null
          finished_at?: string | null
          id?: string
          image_attribution?: string | null
          image_source?: string | null
          image_url?: string | null
          is_picked?: boolean
          options?: Json
          played_at?: string | null
          point_value?: number | null
          prompt?: string
          source?: string
        }
        Relationships: [
          {
            foreignKeyName: "questions_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["id"]
          },
        ]
      }
      reveals: {
        Row: {
          event: string
          game_id: string
          id: string
          metadata: Json | null
          occurred_at: string
          question_id: string
        }
        Insert: {
          event: string
          game_id: string
          id?: string
          metadata?: Json | null
          occurred_at?: string
          question_id: string
        }
        Update: {
          event?: string
          game_id?: string
          id?: string
          metadata?: Json | null
          occurred_at?: string
          question_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "reveals_game_id_fkey"
            columns: ["game_id"]
            isOneToOne: false
            referencedRelation: "games"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reveals_question_id_fkey"
            columns: ["question_id"]
            isOneToOne: false
            referencedRelation: "questions"
            referencedColumns: ["id"]
          },
        ]
      }
      room_magic_reactions: {
        Row: {
          created_at: string
          game_id: string
          id: string
          kind: string
          moment: string
          night_id: string
          player_id: string
          question_id: string
        }
        Insert: {
          created_at?: string
          game_id: string
          id?: string
          kind: string
          moment?: string
          night_id: string
          player_id: string
          question_id: string
        }
        Update: {
          created_at?: string
          game_id?: string
          id?: string
          kind?: string
          moment?: string
          night_id?: string
          player_id?: string
          question_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "room_magic_reactions_game_id_fkey"
            columns: ["game_id"]
            isOneToOne: false
            referencedRelation: "games"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "room_magic_reactions_night_id_fkey"
            columns: ["night_id"]
            isOneToOne: false
            referencedRelation: "nights"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "room_magic_reactions_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "game_scores"
            referencedColumns: ["player_id"]
          },
          {
            foreignKeyName: "room_magic_reactions_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "players"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "room_magic_reactions_question_id_fkey"
            columns: ["question_id"]
            isOneToOne: false
            referencedRelation: "questions"
            referencedColumns: ["id"]
          },
        ]
      }
      topic_suggestions: {
        Row: {
          created_at: string
          id: string
          player_id: string
          text: string
        }
        Insert: {
          created_at?: string
          id?: string
          player_id: string
          text: string
        }
        Update: {
          created_at?: string
          id?: string
          player_id?: string
          text?: string
        }
        Relationships: [
          {
            foreignKeyName: "topic_suggestions_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "game_scores"
            referencedColumns: ["player_id"]
          },
          {
            foreignKeyName: "topic_suggestions_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "players"
            referencedColumns: ["id"]
          },
        ]
      }
      venues: {
        Row: {
          brand_color: string | null
          created_at: string
          host_id: string
          id: string
          name: string
        }
        Insert: {
          brand_color?: string | null
          created_at?: string
          host_id: string
          id?: string
          name: string
        }
        Update: {
          brand_color?: string | null
          created_at?: string
          host_id?: string
          id?: string
          name?: string
        }
        Relationships: [
          {
            foreignKeyName: "venues_host_id_fkey"
            columns: ["host_id"]
            isOneToOne: false
            referencedRelation: "hosts"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      game_scores: {
        Row: {
          answered_count: number | null
          correct_count: number | null
          display_name: string | null
          fastest_correct_ms: number | null
          game_id: string | null
          player_id: string | null
          score: number | null
        }
        Relationships: [
          {
            foreignKeyName: "game_participations_game_id_fkey"
            columns: ["game_id"]
            isOneToOne: false
            referencedRelation: "games"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Functions: {
      _live_claim_command: {
        Args: {
          p_command_id: string
          p_expected_control_revision: number
          p_expected_game_id: string
          p_kind: string
          p_night_id: string
          p_receipt_run_id: string
          p_request_hash: string
        }
        Returns: Json
      }
      _live_existing_command_result: {
        Args: {
          p_command_id: string
          p_night_id: string
          p_request_hash: string
        }
        Returns: Json
      }
      _live_reject_command: {
        Args: { p_code: string; p_command_id: string; p_night_id: string }
        Returns: Json
      }
      _live_resolve_locked_play: {
        Args: {
          p_game_id: string
          p_night_id: string
          p_now: string
          p_play_id: string
          p_run_id: string
        }
        Returns: Json
      }
      _live_scramble_for: {
        Args: { p_player_id: string; p_question_id: string }
        Returns: number[]
      }
      _live_undo_allowed: {
        Args: { p_opened_at: string; p_received_at: string }
        Returns: boolean
      }
      begin_question_play_final_window: {
        Args: {
          p_command_id: string
          p_expected_control_revision: number
          p_game_id: string
          p_play_id: string
          p_run_id: string
        }
        Returns: Json
      }
      current_device_id: { Args: never; Returns: string }
      current_player_id: { Args: { p_night_id: string }; Returns: string }
      end_live_game: {
        Args: {
          p_command_id: string
          p_expected_control_revision: number
          p_game_id: string
          p_run_id: string
        }
        Returns: Json
      }
      finalize_current_play_if_due: {
        Args: { p_play_id: string; p_room_code: string; p_run_id: string }
        Returns: Json
      }
      is_night_host: { Args: { p_night_id: string }; Returns: boolean }
      open_night_run: {
        Args: {
          p_command_id: string
          p_expected_control_revision: number
          p_expected_run_id: string
          p_night_id: string
        }
        Returns: Json
      }
      open_question_play: {
        Args: {
          p_command_id: string
          p_expected_control_revision: number
          p_game_id: string
          p_question_id: string
          p_run_id: string
        }
        Returns: Json
      }
      reset_live_night_to_setup: {
        Args: {
          p_command_id: string
          p_expected_control_revision: number
          p_night_id: string
          p_run_id: string
        }
        Returns: Json
      }
      reset_night_to_setup: { Args: { p_night_id: string }; Returns: Json }
      resolve_question: { Args: { p_question_id: string }; Returns: undefined }
      resolve_question_if_all_locked: {
        Args: { p_question_id: string }
        Returns: boolean
      }
      start_live_game: {
        Args: {
          p_command_id: string
          p_expected_control_revision: number
          p_game_id: string
          p_run_id: string
        }
        Returns: Json
      }
      submit_question_play_answer: {
        Args: {
          p_play_id: string
          p_run_id: string
          p_submission_id: string
          p_verified_device_id: string
          p_visible_slot: number
        }
        Returns: Json
      }
      swap_point_value: {
        Args: { p_point_value: number; p_question_id: string }
        Returns: undefined
      }
      undo_question_play: {
        Args: {
          p_command_id: string
          p_expected_control_revision: number
          p_game_id: string
          p_play_id: string
          p_run_id: string
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const

// Application convenience aliases. These narrow database-enforced shapes
// that the Supabase generator can only express as primitives/JSON.
export type HostRole = "host" | "founder"

export type HostRow = Omit<Tables<"hosts">, "role"> & { role: HostRole }
export type HostInsert = Omit<TablesInsert<"hosts">, "role"> & { role?: HostRole }
export type HostUpdate = Omit<TablesUpdate<"hosts">, "role"> & { role?: HostRole }

export type VenueRow = Tables<"venues">
export type VenueInsert = TablesInsert<"venues">
export type VenueUpdate = TablesUpdate<"venues">

export type NightRow = Omit<
  Tables<"nights">,
  | "answer_engine"
  | "answer_engine_latched_at"
  | "current_run_id"
  | "room_revision"
  | "control_revision"
> & {
  answer_engine?: string
  answer_engine_latched_at?: string | null
  current_run_id?: string | null
  room_revision?: number
  control_revision?: number
}
export type NightInsert = TablesInsert<"nights">
export type NightUpdate = TablesUpdate<"nights">

export type GameRow = Omit<Tables<"games">, "game_no" | "state"> & {
  game_no: 1 | 2
  state: "draft" | "ready" | "live" | "done"
}
export type GameInsert = Omit<TablesInsert<"games">, "game_no" | "state"> & {
  game_no: 1 | 2
  state?: "draft" | "ready" | "live" | "done"
}
export type GameUpdate = Omit<TablesUpdate<"games">, "game_no" | "state"> & {
  game_no?: 1 | 2
  state?: "draft" | "ready" | "live" | "done"
}

export type CategoryRow = Omit<Tables<"categories">, "state"> & {
  state: "draft" | "generating" | "review" | "ready"
}
export type CategoryInsert = Omit<TablesInsert<"categories">, "state"> & {
  state?: "draft" | "generating" | "review" | "ready"
}
export type CategoryUpdate = Omit<TablesUpdate<"categories">, "state"> & {
  state?: "draft" | "generating" | "review" | "ready"
}

export type QuestionRow = Omit<
  Tables<"questions">,
  "options" | "correct_index" | "point_value"
> & {
  options: [string, string, string, string]
  correct_index: 0 | 1 | 2 | 3
  point_value: 100 | 200 | 300 | 400 | 500 | 600 | 700 | null
}
export type QuestionInsert = Omit<
  TablesInsert<"questions">,
  "options" | "correct_index" | "point_value"
> & {
  options: [string, string, string, string]
  correct_index: 0 | 1 | 2 | 3
  point_value?: 100 | 200 | 300 | 400 | 500 | 600 | 700 | null
}
export type QuestionUpdate = Omit<
  TablesUpdate<"questions">,
  "options" | "correct_index" | "point_value"
> & {
  options?: [string, string, string, string]
  correct_index?: 0 | 1 | 2 | 3
  point_value?: 100 | 200 | 300 | 400 | 500 | 600 | 700 | null
}

export type PlayerRow = Omit<Tables<"players">, "can_answer"> & {
  can_answer?: boolean
}
export type PlayerInsert = TablesInsert<"players">
export type PlayerUpdate = TablesUpdate<"players">

export type ParticipationRow = Tables<"game_participations">
export type ParticipationInsert = TablesInsert<"game_participations">
export type ParticipationUpdate = TablesUpdate<"game_participations">

export type AnswerRow = Omit<Tables<"answers">, "scramble" | "chosen_index"> & {
  scramble: [number, number, number, number]
  chosen_index: 0 | 1 | 2 | 3
}
export type AnswerInsert = Omit<TablesInsert<"answers">, "scramble" | "chosen_index"> & {
  scramble: [number, number, number, number]
  chosen_index: 0 | 1 | 2 | 3
}
export type AnswerUpdate = Omit<TablesUpdate<"answers">, "scramble" | "chosen_index"> & {
  scramble?: [number, number, number, number]
  chosen_index?: 0 | 1 | 2 | 3
}

export type RevealRow = Omit<Tables<"reveals">, "event"> & {
  event: "reveal" | "undo" | "end-early" | "resolve"
}
export type RevealInsert = Omit<TablesInsert<"reveals">, "event"> & {
  event: "reveal" | "undo" | "end-early" | "resolve"
}
export type RevealUpdate = Omit<TablesUpdate<"reveals">, "event"> & {
  event?: "reveal" | "undo" | "end-early" | "resolve"
}

export type RoomMagicReactionRow = Tables<"room_magic_reactions">
export type RoomMagicReactionInsert = TablesInsert<"room_magic_reactions">
export type RoomMagicReactionUpdate = TablesUpdate<"room_magic_reactions">
export type AdjustmentRow = Tables<"adjustments">
export type AdjustmentInsert = TablesInsert<"adjustments">
export type AdjustmentUpdate = TablesUpdate<"adjustments">
export type TopicSuggestionRow = Tables<"topic_suggestions">
export type TopicSuggestionInsert = TablesInsert<"topic_suggestions">
export type TopicSuggestionUpdate = TablesUpdate<"topic_suggestions">
export type AudienceTopicVoteRow = Tables<"audience_topic_votes">
export type AudienceTopicVoteInsert = TablesInsert<"audience_topic_votes">
export type AudienceTopicVoteUpdate = TablesUpdate<"audience_topic_votes">
export type QuestionGenerationReportRow = Tables<"question_generation_reports">
export type QuestionGenerationReportInsert = TablesInsert<"question_generation_reports">
export type QuestionGenerationReportUpdate = TablesUpdate<"question_generation_reports">
export type GameScoreRow = Tables<"game_scores">
